version: "3.9"

services:
  # ------------------ Config Server ------------------
  config-server:
    build: ../backend/config-server
    container_name: config-server
    ports:
      - "8888:8888"

  # ------------------ Eureka Server ------------------
  eureka-server:
    build: ../backend/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  # ------------------ Gateway Service ------------------
  gateway-service:
    build: ../backend/gateway-service
    container_name: gateway-service
    ports:
      - "8085:8085"
    depends_on:
      - config-server
      - eureka-server

  # ------------------ Controle Database ------------------
  controle-db:
    image: mysql:8.0
    container_name: controle-db
    environment:
      MYSQL_DATABASE: control_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - controle-db-data:/var/lib/mysql

  # ------------------ Controle Service ------------------
  controle-service:
    build: ../backend/controle-service
    container_name: controle-service
    depends_on:
      - controle-db
      - config-server
      - eureka-server
      - gateway-service
      - rabbitmq
    ports:
      - "8087:8087"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    command: ["./wait-for-it.sh", "controle-db:3306", "--timeout=60", "--", "java", "-jar", "app.jar"]

  # ------------------ Environment Database ------------------
  environment-db:
    image: mysql:8.0
    container_name: environment-db
    environment:
      MYSQL_DATABASE: environment_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    volumes:
      - environment-db-data:/var/lib/mysql

  # ------------------ Environment Service ------------------
  environment-service:
    build: ../backend/environment-service
    container_name: environment-service
    depends_on:
      - environment-db
      - config-server
      - eureka-server
      - gateway-service
      - rabbitmq
    ports:
      - "8089:8089"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    command: ["./wait-for-it.sh", "environment-db:3306", "--timeout=60", "--", "java", "-jar", "app.jar"]

  # ------------------ RabbitMQ ------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Dashboard web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

# ------------------ Volumes ------------------
volumes:
  controle-db-data:
  environment-db-data:
